deploy:
  runs-on: ubuntu-latest
  needs: docker
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Kind Cluster
      uses: helm/kind-action@v1

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0

    - name: Deploy with Helm
      run: |
        helm upgrade --install bookstore ./helm/bookstore-api \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/bookstore-api \
          --set image.tag=latest

    - name: Wait for deployment rollout
      run: |
        DEPLOYMENT_NAME=$(kubectl get deploy -l app.kubernetes.io/name=bookstore-api -o jsonpath='{.items[0].metadata.name}')
        echo "Detected Deployment: $DEPLOYMENT_NAME"
        kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=60s

    - name: Port-forward and test API
      run: |
        SERVICE_NAME=$(kubectl get svc -l app.kubernetes.io/name=bookstore-api -o jsonpath='{.items[0].metadata.name}')
        echo "Detected Service: $SERVICE_NAME"
        kubectl port-forward svc/$SERVICE_NAME 8080:8080 &
        sleep 5
        curl -f http://localhost:8080/books/ || exit 1
